import { PromptData } from '../types/prompt';

export const generateXML = (data: PromptData): string => {
  const escapeXML = (str: string): string => {
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&apos;');
  };

  return `<?xml version="1.0" encoding="UTF-8"?>
<video-prompt>
  <metadata>
    <created>${new Date().toISOString()}</created>
    <version>1.0</version>
  </metadata>
  <content>
    <scene>${escapeXML(data.scene)}</scene>
    <visual-style>${escapeXML(data.visualStyle)}</visual-style>
    <camera>
      <movement>${escapeXML(data.cameraMovement)}</movement>
    </camera>
    <lighting>${escapeXML(data.lighting)}</lighting>
    <mood>${escapeXML(data.mood)}</mood>
  </content>
  <technical-specs>
    <duration>${escapeXML(data.duration)}</duration>
    <aspect-ratio>${escapeXML(data.aspectRatio)}</aspect-ratio>
    <fps>${escapeXML(data.fps)}</fps>
    <resolution>${escapeXML(data.resolution)}</resolution>
  </technical-specs>
  ${data.additionalParams ? `<additional-parameters>\n    ${escapeXML(data.additionalParams)}\n  </additional-parameters>` : ''}
</video-prompt>`;
};

export const generateMarkdown = (data: PromptData): string => {
  const timestamp = new Date().toLocaleString();
  
  return `# AI Video Prompt

**Generated:** ${timestamp}

---

## Scene Description
${data.scene || '_No scene description provided_'}

## Visual Style
${data.visualStyle || '_No visual style specified_'}

## Camera Movement
${data.cameraMovement || '_No camera movement specified_'}

## Lighting
${data.lighting || '_No lighting specified_'}

## Mood & Atmosphere
${data.mood || '_No mood specified_'}

---

## Technical Specifications

| Parameter | Value |
|-----------|-------|
| Duration | ${data.duration || 'Not specified'} |
| Aspect Ratio | ${data.aspectRatio} |
| FPS | ${data.fps} |
| Resolution | ${data.resolution} |

${data.additionalParams ? `\n---\n\n## Additional Parameters\n\n${data.additionalParams}` : ''}

---

*Generated by AI Video Prompt Creator*
`;
};

export const downloadFile = (content: string, filename: string, mimeType: string) => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const copyToClipboard = async (text: string): Promise<boolean> => {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (err) {
    console.error('Failed to copy:', err);
    return false;
  }
};
